spring.application.name=themealdb-explorer-api

# TheMealDB API Configuration
themealdb.base-url=https://www.themealdb.com/api/json/v1/1/

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.chinmay.themealdbexplorerapi=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Cache Configuration
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m
